network:
  version: 2
  renderer: NetworkManager
  ethernets:
    # USB to Ethernet converter (WAN).
    enx503f56022324:
      dhcp4: false
      dhcp6: false
    # On-board ethernet port (LAN).
    eno2:
      dhcp4: false
      dhcp6: false
  # Create bridge interfaces to expose to router and additional VMs.
  bridges:
    br-lan:
      addresses: [10.1.0.10/24]
      interfaces: [eno2]
      routes:
        - to: 10.1.0.0/24
          via: 10.1.0.1
    br-wan:
      addresses: [192.168.1.84/24]
      interfaces: [enx503f56022324]
      routes:
        - to: default
          via: 192.168.1.1
      nameservers:
        addresses: [8.8.8.8]
